# Generated by Django 2.2.3 on 2019-09-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Player name', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_x_score', models.IntegerField(default=0)),
                ('player_o_score', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=None)),
                ('player_o', models.ForeignKey(help_text='A player representing O', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_player_o', to='tic_tac_toe.Player')),
                ('player_x', models.ForeignKey(help_text='A player representing X', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_player_x', to='tic_tac_toe.Player')),
            ],
        ),
    ]
