# Generated by Django 2.2.5 on 2019-09-03 18:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0002_game_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), size=3), size=3)),
                ('game', models.ForeignKey(help_text='Current game', null=True, on_delete=django.db.models.deletion.CASCADE, to='tic_tac_toe.Game')),
                ('winner', models.ForeignKey(help_text='A player representing O', null=True, on_delete=django.db.models.deletion.CASCADE, to='tic_tac_toe.Player')),
            ],
        ),
    ]
