# Generated by Django 2.2.5 on 2019-09-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0003_gameround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='highest_score',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
