# Generated by Django 2.2.5 on 2019-09-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0004_auto_20190906_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(default=None, help_text='Winner of the game', on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to='tic_tac_toe.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_o',
            field=models.ForeignKey(default=None, help_text='A player representing O', on_delete=django.db.models.deletion.CASCADE, related_name='game_player_o', to='tic_tac_toe.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_x',
            field=models.ForeignKey(default=None, help_text='A player representing X', on_delete=django.db.models.deletion.CASCADE, related_name='game_player_x', to='tic_tac_toe.Player'),
        ),
    ]
