# Generated by Django 2.2.5 on 2019-09-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0005_auto_20190906_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(default=None, help_text='Winner of the game', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to='tic_tac_toe.Player'),
        ),
    ]
