# Generated by Django 2.2.5 on 2019-09-07 09:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0006_auto_20190906_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), size=6), size=6),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='winner',
            field=models.ForeignKey(help_text='Winner of the round', null=True, on_delete=django.db.models.deletion.CASCADE, to='tic_tac_toe.Player'),
        ),
    ]
